=== Web-Dev-Collaborative/UsefulResourceRepo2.0/_REPO/APRESS/pro-design-patterns-in-vb.net/6985/Ch03/TestHarness/bin/Order.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" attributeFormDefault="qualified" elementFormDefault="qualified">
	<xs:element name="Order">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Product" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string" minOccurs="0" msdata:Ordinal="0" />
							<xs:element name="Quantity" type="xs:positiveInteger" minOccurs="0" msdata:Ordinal="1" />
							<xs:element name="Price" type="xs:double" minOccurs="0" msdata:Ordinal="2" />
							<xs:element name="RequiredDate" type="xs:date" minOccurs="0" msdata:Ordinal="3" />
						</xs:sequence>
						<xs:attribute name="ProductID" form="unqualified" type="xs:positiveInteger" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="CustomerID" form="unqualified" type="xs:string" />
			<xs:attribute name="OrderDate" form="unqualified" type="xs:date" />
		</xs:complexType>
	</xs:element>
	<xs:element name="NewDataSet" msdata:IsDataSet="true" msdata:EnforceConstraints="False">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="Order" />
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Web-Dev-Collaborative/UsefulResourceRepo2.0/_REPO/APRESS/pro-design-patterns-in-vb.net/6985/Ch03/TestHarness/bin/Order.xml
<?xml version="1.0" ?>
<Order CustomerID="ALFKI" OrderDate="2002-06-11" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Order.xsd">
	<Product ProductID="61">
		<Name>Sirop d'erable</Name>
		<Quantity>5</Quantity>
		<Price>28.50</Price>
		<RequiredDate>2002-08-01</RequiredDate>
	</Product>
	<Product ProductID="69">
		<Name>Gudbrandsdalsost</Name>
		<Quantity>5</Quantity>
		<Price>36.00</Price>
		<RequiredDate>2002-08-01</RequiredDate>
	</Product>
	<Product ProductID="75">
		<Name>Rhonbrau Klosterbier</Name>
		<Quantity>5</Quantity>
		<Price>7.75</Price>
		<RequiredDate>2002-09-01</RequiredDate>
	</Product>
</Order>
