=== Web-Dev-Collaborative/UsefulResourceRepo2.0/_REPO/APRESS/pro-design-patterns-in-vb.net/6985/Ch03/TestHarness/bin/SpecialOrder.dtd
<!ELEMENT SpecialOrder (Product)* >
<!ATTLIST SpecialOrder CustomerID CDATA #REQUIRED>
<!ATTLIST SpecialOrder OrderDate CDATA #REQUIRED>
<!ELEMENT Product (Name, Quantity, Price)>
<!ATTLIST Product ProductID CDATA #REQUIRED>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Quantity (#PCDATA)>
<!ELEMENT Price (#PCDATA)>

=== Web-Dev-Collaborative/UsefulResourceRepo2.0/REPO/supertemp/APRESS/pro-design-patterns-in-vb.net/6985/Ch03/TestHarness/bin/SpecialOrder.xml
<?xml version="1.0"?>
<!DOCTYPE OldOrder SYSTEM "SpecialOrder.dtd">
<SpecialOrder CustomerID="ALFKI" OrderDate="6/1/2002">
<Product ProductID="1">
	<Name>Chai</Name>
	<Quantity>5</Quantity>
	<Price>18.00</Price>
</Product>
<Product ProductID="2">
	<Name>Chang</Name>
	<Quantity>10</Quantity>
	<Price>19.00</Price>
</Product>
</SpecialOrder>
